import type { Product } from './types';

export const psm_1Products: Product[] = [
  {
    id: 1,
    title: 'Крышка НТ.3.05.00.00.000',
    description: '',
    price: '14 000',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '',
  },
  {
    id: 2,
    title: 'Емкость НТ.3.01.00.00.000',
    description: '',
    price: '9 500',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных день',
    image: '',
  },
  {
    id: 3,
    title: 'Трубка НТ.3.03.00.00.000',
    description: '',
    price: '5 500',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '',
  },
  {
    id: 4,
    title: 'Фильтр НТ.3.04.04.00.000',
    description: '',
    price: '3 550',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '',
  },
  {
    id: 5,
    title: 'Сухарь НТ.3.00.00.00.005',
    description: '',
    price: '500',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '',
  },
  {
    id: 6,
    title: 'Клапан предохранительный НТ.3.02.00.00.000',
    description: '',
    price: '3 600',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '',
  },
  {
    id: 7,
    title: 'Прокладка НТ.3.00.00.00.006',
    description: '',
    price: '500',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '',
  },
];