import type { Product } from './types';

export const psm_1Products: Product[] = [
  {
    id: 1,
    title: 'Диск НТ.103.000.002-01 (8скв)',
    description: '',
    price: '1 500',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/psm/1.webp',
  },
  {
    id: 2,
    title: 'Крышка ПСМНТ.001.011.000-01',
    description: '',
    price: '150 000',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных день',
    image: '/images/shop/psm/крышка_1.webp',
  },
  {
    id: 3,
    title: 'Вал ПСМНТ.001.015.000',
    description: '',
    price: '83 100',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/psm/вал.webp',
  },
  {
    id: 4,
    title: 'Колодка клеммная ПСМНТ.001.016.000',
    description: '',
    price: '3 600',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/psm/колодка.webp',
  },
  {
    id: 5,
    title: 'Крышка ПСМНТ.001.000.001 (с маркировкой)',
    description: '',
    price: '5 100',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/psm/крышка_2.webp',
  },
  {
    id: 6,
    title: 'Корпус ПСМНТ.001.018.000-02 (8 скв) — наплавка',
    description: '',
    price: '230 000',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/psm/корпус_1.webp',
  },
  {
    id: 7,
    title: 'Датчик положения ПСМ.11.00.00.00(8 скважин)',
    description: '',
    price: '21 000',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '',
  },
  {
    id: 8,
    title: 'Указатель ПСМНТ.001.021.000',
    description: '',
    price: '2 500',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/psm/указатель.webp',
  },
  {
    id: 9,
    title: 'Каретка ПСМНТ.001.022.000',
    description: '',
    price: '36 700',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/psm/каретка.webp',
  },
  {
    id: 10,
    title: 'Угольник ПСМНТ.001.029.000 СБ',
    description: '',
    price: '31 200',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/psm/угольник.webp',
  },
  {
    id: 11,
    title: 'Подпятник ПСМНТ.001.000.002',
    description: '',
    price: '450',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '',
  },
  {
    id: 12,
    title: 'Поршень ПСМНТ.001.000.003',
    description: '',
    price: '3 300',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '',
  },
  {
    id: 13,
    title: 'Корпус ПСМНТ.001.000.005 (литье - СЧ18 ГОСТ 1412-85)',
    description: '',
    price: '90 500',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/psm/корпус_2.webp',
  },
  {
    id: 14,
    title: 'Корпус ПСМНТ.001.000.006',
    description: '',
    price: '50 500',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/psm/корпус_3.webp',
  },
  {
    id: 15,
    title: 'Крышка ПСМНТ.001.000.007',
    description: '',
    price: '3 000',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/psm/крышка_3.webp',
  },
  {
    id: 16,
    title: 'Гильза ПСМНТ.001.000.008',
    description: '',
    price: '6 000',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '',
  },
  {
    id: 17,
    title: 'Кольцо ПСМНТ.001.000.009',
    description: '',
    price: '3 000',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/psm/кольцо.webp',
  },
  {
    id: 18,
    title: 'Кольцо ПСМНТ.001.000.010',
    description: '',
    price: '2 500',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/psm/кольцо уплотнения.webp',
  },
  {
    id: 19,
    title: ' Кольцо ПСМНТ.001.000.010-03',
    description: '',
    price: '2 500',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '',
  },
  {
    id: 20,
    title: 'Кольцо ПСМНТ.001.000.010-05',
    description: '',
    price: '2 500',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '',
  },
  {
    id: 21,
    title: 'Храповик ПСМНТ.001.000.011-02 (8 скв)',
    description: '',
    price: '14 500',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/psm/храповик.webp',
  },
  {
    id: 22,
    title: 'Пружина ПСМНТ.001.000.013 (крашенная)',
    description: '',
    price: '4 200',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/psm/пружина.webp',
  },
  {
    id: 23,
    title: 'Колесо зубчатое ПСМНТ.001.000.014-02 (8 скв)',
    description: '',
    price: '15 000',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/psm/колесо_зубчист.webp',
  },
  {
    id: 24,
    title: ' Пробка ПСМНТ.001.000.016',
    description: '',
    price: '800',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/psm/пробка.webp',
  },
  {
    id: 25,
    title: 'Пробка ПСМНТ.001.000.017',
    description: '',
    price: '600',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '',
  },
  {
    id: 26,
    title: 'Шпилька ПСМНТ.001.000.020',
    description: '',
    price: '800',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '',
  },
  {
    id: 27,
    title: 'Ось-винт ПСМНТ.001.022.006',
    description: '',
    price: '900',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/psm/винт.webp',
  },
  {
    id: 28,
    title: 'Бобышка ПСМНТ.001.000.022',
    description: '',
    price: '350',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '',
  },
  {
    id: 29,
    title: 'Ролик ПСМНТ.001.022.005',
    description: '',
    price: '1 500',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/psm/ролик.webp',
  },
  {
    id: 30,
    title: 'Кольцо ПСМНТ.001.000.029',
    description: '',
    price: '350',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '',
  },
  {
    id: 31,
    title: 'Втулка ПСМНТ.001.000.031',
    description: '',
    price: '300',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/psm/втулка.webp',
  },
];