import type { Product } from './types';

export const urpd1Products: Product[] = [
  {
    id: 1,
    title: 'Рычаг НТ.510.000.003.0',
    description: '',
    price: '2 820',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/urpd/1.webp',

  },
  {
    id: 2,
    title: 'Валик НТ.511.000.004.0',
    description: '',
    price: '5 280',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных день',
    image: '/images/shop/urpd/2.webp',
  },
  {
    id: 3,
    title: 'Шибер НТ.511.000.005.0',
    description: '',
    price: '5 115',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/urpd/2-3.webp',
  },
  {
    id: 4,
    title: 'Подшипник НТ.510.000.006.0',
    description: '',
    price: '450',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/urpd/4.webp',
  },
  {
    id: 5,
    title: 'Уплотнение корпуса НТ.511.000.007.0',
    description: '',
    price: '5 200',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '',
  },
  {
    id: 6,
    title: 'Уплотнение крышки НТ.511.000.008.0',
    description: '',
    price: '5 200',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '',
  },
  {
    id: 7,
    title: 'Кольцо фторопластовое НТ.510.000.009.0',
    description: '',
    price: '1 590',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/urpd/2-6.webp',
  },
  {
    id: 8,
    title: 'Кольцо уплотнения 049-055-36 – 2шт.',
    description: '',
    price: '1 590',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '',
  },
  {
    id: 9,
    title: 'Кольцо уплотнения валика 014-018-25 – 2шт.',
    description: '',
    price: '1 215',
    nds: 'без НДС',
    deliveryTime: '60–90 календарных дней',
    image: '/images/shop/urpd/2-8.webp',
  },
];